# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_time', models.DateTimeField(auto_now_add=True)),
                ('humidity', models.CharField(blank=True, max_length=10)),
                ('temperature', models.CharField(blank=True, max_length=10)),
                ('light_exposure', models.CharField(blank=True, max_length=10)),
                ('uv_level', models.CharField(blank=True, max_length=10)),
                ('soil_moisture', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
